// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Screens.data;

#nullable disable

namespace Screens.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260420093043_Screens")]
    partial class Screens
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Screens.Models.Image", b =>
                {
                    b.Property<int>("imageID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("imageID"));

                    b.Property<string>("imageBath")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("imageDescription")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("imageOrder")
                        .HasColumnType("int");

                    b.Property<int>("imageScreenId")
                        .HasColumnType("int");

                    b.Property<string>("imageTitle")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("image_status")
                        .HasColumnType("int");

                    b.Property<DateTime>("imagefromDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("imagetoDate")
                        .HasColumnType("datetime2");

                    b.HasKey("imageID");

                    b.HasIndex("imageScreenId");

                    b.ToTable("images");
                });

            modelBuilder.Entity("Screens.Models.Screen", b =>
                {
                    b.Property<int>("screenId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("screenId"));

                    b.Property<string>("screenDescription")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("screenName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("screenStatus")
                        .HasColumnType("bit");

                    b.HasKey("screenId");

                    b.ToTable("screens");
                });

            modelBuilder.Entity("Screens.Models.Image", b =>
                {
                    b.HasOne("Screens.Models.Screen", "screen")
                        .WithMany("Images")
                        .HasForeignKey("imageScreenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("screen");
                });

            modelBuilder.Entity("Screens.Models.Screen", b =>
                {
                    b.Navigation("Images");
                });
#pragma warning restore 612, 618
        }
    }
}
